In [2]:
import numpy as np

In [11]:
arr = np.array([1,2,3],dtype = 'int16')
arr

array([1, 2, 3], dtype=int16)

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr.shape

(2, 3)

In [13]:
arr.dtype

dtype('int16')

In [12]:
#4 if int32
arr.itemsize

2

In [15]:
#no of elements 
arr.nbytes

6

## Accessing/Changing specific elements rows, columns etc

In [3]:
arr = np.array([[1,2,3,5,6,7,8,9],[4,5,6,7,8,9,10,11]])

In [4]:
arr.shape

(2, 8)

In [5]:
arr[1,4]

8

In [6]:
arr[0,:]

array([1, 2, 3, 5, 6, 7, 8, 9])

In [8]:
arr[:,1]

array([2, 5])

In [10]:
arr[1,1:6:2]

array([5, 7, 9])

In [12]:
arr[1,4] = 100
arr

array([[  1,   2,   3,   5,   6,   7,   8,   9],
       [  4,   5,   6,   7, 100,   9,  10,  11]])

In [13]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
a[0,1,1]

4

## Initializing different types of array

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2,4),dtype='int16')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [21]:
np.full((3,6),707)

array([[707, 707, 707, 707, 707, 707],
       [707, 707, 707, 707, 707, 707],
       [707, 707, 707, 707, 707, 707]])

In [22]:
np.full_like(a,101)

array([[[101, 101],
        [101, 101]],

       [[101, 101],
        [101, 101]]])

In [23]:
#Random integers between 0 and 1
np.random.rand(3,3)

array([[0.56220434, 0.85640338, 0.16900991],
       [0.37595728, 0.17270512, 0.16969135],
       [0.02384427, 0.43901495, 0.97923184]])

In [25]:
np.random.random_sample(a.shape)

array([[[0.61581644, 0.79462235],
        [0.2613928 , 0.51137532]],

       [[0.60258602, 0.87350348],
        [0.4465111 , 0.24178166]]])

In [32]:
#Random integers between 0 and 4
np.random.randint(0,4,size=(3,3))

array([[2, 1, 3],
       [0, 3, 3],
       [1, 3, 1]])

In [33]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
#repeat a array axis=1-->columns wise axis=0-->row wise
a1 = np.array([[1,2,3]])
np.repeat(a1,3,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [50]:
#QUIZ
q= np.zeros((5,5))
q[1:4,1:4] = 1 
q[2,2] = 9
q

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 9., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

## Mathematics

In [51]:
a = np.array([1,2,3,4,5])

In [52]:
a*2

array([ 2,  4,  6,  8, 10])

In [53]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [54]:
a+2

array([3, 4, 5, 6, 7])

In [55]:
a-2

array([-1,  0,  1,  2,  3])

In [56]:
b = np.array([6,7,8,9,10])
b-a

array([5, 5, 5, 5, 5])

In [57]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [64]:
#Matrices should be compatible
a = np.array([[1,2,],[4,5,],[1,2]])
b = np.array([[4,5,6],[7,8,9]])
np.matmul(a,b)

array([[18, 21, 24],
       [51, 60, 69],
       [18, 21, 24]])

## Statistics

In [66]:
b = np.array([[4,5,6],[7,8,9]])
np.min(b)

4

In [67]:
np.min(b,axis=1)

array([4, 7])

In [68]:
np.max(b,axis=0)

array([7, 8, 9])

In [69]:
np.sum(b,axis=0)

array([11, 13, 15])

In [73]:
print(b.shape)
a = b.reshape(6,1)
print(a)

(2, 3)
[[4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [76]:
b = np.array([[4,5,6],[7,8,9]])
a = np.array([[4,5,6],[7,8,9]])
print(np.vstack([a,b]))
print(np.hstack([a,b]))

[[4 5 6]
 [7 8 9]
 [4 5 6]
 [7 8 9]]
[[4 5 6 4 5 6]
 [7 8 9 7 8 9]]


## Data, Boolean Masking

data =np.genfromtxt('data.txt',delimiter = ',') #read data from file
data.astype('int32') #convert data into suitable datatype

data[data > 50]  #Indexing based on conditions


In [79]:
b = np.array([4,5,6,7,8,9])
b[[1,2,3]]

array([5, 6, 7])

In [80]:
b[b>5]

array([6, 7, 8, 9])